name: Build Evaluation Function Image

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    uses: lambda-feedback/evaluation-function-workflows/.github/workflows/lean_test.yml@main
    with:
      lint-module: "Evaluation"

  build:
    uses: lambda-feedback/evaluation-function-workflows/.github/workflows/build.yml@main
    needs: [test]
    with:
      template-repository-name: 'lambda-feedback/evaluation-function-boilerplate-lean'
      build-args: |
        LEAN_VERSION=${{ needs.test.outputs.lean-version }}
